### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by areindl** [supercharge/promise-pool#28]
Hi guys! Thanks for your work. It really helped me in making my Cloud Functions development more enjoyable.

I have a questions that is not `promise-pool` related but JavaScript oriented. I still hope you can help me with a quick hint as it might be obvious for you and could be helpful as a documentation example 👍 

In your example to provided the following:

```javascript
const { results, errors } = await PromisePool
  .withConcurrency(2)
  .for(users)
  .process(async data => {
    const user = await User.createIfNotExisting(data)

    return user
  })
```

I am particularly interested in looking at the errors. However I did not really understand how I can access the errors-Object. I know this is a JavaScript-Beginner question, so sorry about this.

I ended up doing this:

```javascript
 const addedUsers = await PromisePool.withConcurrency(3)
 ...
 ```
 
 And then looking into the errors like:
 ```javascript
if (addedUsers.errors.length) {
...
 ...
 ```
 
 But that's not a very sleek solution. Any hint how to handle the errors better?
 
 Thank you in advance.

**Comment by marcuspoehls** [comment]
@areindl Hey Anton, good question!

We use a promise pool to process a given number of items concurrently. At the same time, this may also produce a given amount of errors. While using a promise pool in our projects, we have two error handling strategies:


## Error Handling Strategy 1: All or nothing
Sometimes we want all items in the pool to be processed and stored in a database. We typically use this approach when importing data. This way we can restart the import process for the whole file instead of individual items.

Here’s a sample code using a database transaction to either commit or rollback at the end.

```
const trx = await Database.createTransaction()

const { errors } = await PromisePool.for(items).process(async item => {
  await Database.store(item, trx)
})

errors.length
  ? await trx.rollback()
  : await trx.commit()
```


## Error Handling Strategy 2: En-queue failed items for another try
In specific situations, we re-try the processing of items. For example, you may enqueue a queue job to re-try the failed items.

```
const { errors } = await PromisePool.for(users).process(async user => {
  await UserModel.subscribeToNewsletter(user)
})

if (errors.length) {
  await SubscribeUsers.dispatch({
    userIds: errors.map(error => error.user.id)
  })
}
```

@areindl Anton, does this help?

**Comment by marcuspoehls** [comment]
@areindl Anton, I assume my answer is OK for you. Closing this issue here. Please re-open or reach out again if you need any help 😃

**Comment by areindl** [comment]
Hi @marcuspoehls!

Sorry for my late response. I was caught up in another topics. Your approach totally makes sense.

I applied it today and it looks much cleaner.

Thanks a lot! 

PS: Nice podcast ;-)

**Comment by marcuspoehls** [comment]
@areindl Hey Anton, that’s great! I’m happy you’re able to apply ideas in your code. And thank you for the note on the podcast 😍
