### ISSUE TITLE
Browser use causes Critical Dependency Webpack error

### ISSUE THREAD

**Issue by rijkvanzanten** [supercharge/promise-pool#30]
Hi there!

I fully realize that Supercharge is designed and built as a Node framework. That being said, a util like PromisePool is really useful for client-side applications as well.

However, due to the way `@supercharge/goodies` is built, bundling `@supercharge/promise-pool` into a front-end context throws the following warning on builds (with Webpack):

```
WARNING  Compiled with 1 warning
Critical dependency: the request of a dependency is an expression
warning  in ./node_modules/@supercharge/goodies/dist/goodies.js
```

**Comment by rijkvanzanten** [comment]
I believe that the warning is caused by the `esmRequire` util added to `goodies` in c20668a37b5d753ea18ea001c10fb6a0ed39a1bf:

https://github.com/supercharge/goodies/blob/4c9d5b21e501aa6e14aa63d483ae694461315c9c/src/index.ts#L130-L140

**Comment by marcuspoehls** [comment]
@rijkvanzanten Hey Rijk, yeah that’s true. `@supercharge/goodies` is currently built using a class which makes it not tree-shakable.

I’m assuming you’re trying to use this promise pool package in the frontend. Is that true?

We can rewrite this `@supercharge/promise-pool` package to remove the `@supercharge/goodies` dependency. Or another option is to refactor `@supercharge/goodies` to be tree-shakable and webpack-ready. Unfortunately, I’m currently short on time and it would take me a week or two to rewrite the goodies package.

**Comment by rijkvanzanten** [comment]
I had a quick peek through the goodies package which made me wonder: is there a need for it to be a class instead of a list of exported functions? I can look into making a start on that refactoring process, but rather not waste any time if there's a hard requirement for it to be this way of course :)

**Comment by marcuspoehls** [comment]
You’re right: the goodies package can export the available functions. It doesn’t need the class requirement. I started a quick refactoring process and pushed it to the [refactor-to-functions](https://github.com/supercharge/goodies/tree/refactor-to-functions) branch. It’s basically the move to exported functions :)

Tests are yet failing due to a peer dependency for the standard linting. I’ll probably have a look at it tomorrow or on Monday.

Please feel free to send pull requests updating the functionality to your needs! I’m happy to support you in any way 👍

**Comment by rijkvanzanten** [comment]
Loooooooking good! ❤️

**Comment by marcuspoehls** [comment]
Awesome 🙌
